// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqi6hbY3uYiXfSdsw-d5UtoG6cU4FbGY',
    appId: '1:1095384619265:web:f5089db0f3bedf58dbe300',
    messagingSenderId: '1095384619265',
    projectId: 'latihan-1-55dec',
    authDomain: 'latihan-1-55dec.firebaseapp.com',
    storageBucket: 'latihan-1-55dec.appspot.com',
    measurementId: 'G-PXH2EYESG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9TO3qPsT_jMU__Bct3QIauFmniztNl8',
    appId: '1:1095384619265:android:9f89c962de67b339dbe300',
    messagingSenderId: '1095384619265',
    projectId: 'latihan-1-55dec',
    storageBucket: 'latihan-1-55dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ji1EcTw-xToDya86bUauigpOyRtyyuU',
    appId: '1:1095384619265:ios:560934f7d6e11a17dbe300',
    messagingSenderId: '1095384619265',
    projectId: 'latihan-1-55dec',
    storageBucket: 'latihan-1-55dec.appspot.com',
    iosClientId: '1095384619265-o0sdp3s8lmq7ie7q6j5kt559sn904t49.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ji1EcTw-xToDya86bUauigpOyRtyyuU',
    appId: '1:1095384619265:ios:101694e6c1a0ca6fdbe300',
    messagingSenderId: '1095384619265',
    projectId: 'latihan-1-55dec',
    storageBucket: 'latihan-1-55dec.appspot.com',
    iosClientId: '1095384619265-dt65hvrgflo54bbs6v5qlgfr3tkdojo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
